# Generated by Django 5.2.15 on 2026-06-24 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_categoriasplato_nombre_categoria'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('secuencial', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('cliente_nombre', models.CharField(default='Consumidor Final', max_length=150)),
                ('cliente_identificacion', models.CharField(default='9999999999999', max_length=13, verbose_name='Cédula/RUC')),
                ('cliente_correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], default='efectivo', max_length=20)),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cajero', models.ForeignKey(db_column='id_cajero', on_delete=django.db.models.deletion.RESTRICT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='pedidos.gestionpedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id_factura_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_historico', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='facturacion.factura')),
                ('id_platillo', models.ForeignKey(db_column='id_platillo', on_delete=django.db.models.deletion.RESTRICT, to='menu.gestionplatillo')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
                'db_table': 'factura_detalle',
            },
        ),
    ]
