# Generated by Django 5.2.15 on 2026-06-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(default='S/N', max_length=250, verbose_name='Dirección'),
        ),
    ]
