# Generated by Django 5.2.15 on 2026-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(default='Sabor y Arte', max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(default='20456789012', max_length=13, verbose_name='RUC del Establecimiento')),
                ('provincia', models.CharField(default='Manta, Manabí', max_length=100, verbose_name='Ciudad / Provincia')),
                ('direccion', models.CharField(default='Av. Gastronomía 455, Miraflores', max_length=255, verbose_name='Dirección Matriz')),
                ('iva_porcentaje', models.IntegerField(default=12, verbose_name='Tasa de IVA Vigente (%)')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
                'db_table': 'configuracion_facturacion',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor_nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor_provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor_razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor_ruc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva_porcentaje_aplicado',
            field=models.IntegerField(default=12, verbose_name='Porcentaje IVA Aplicado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(blank=True, default='S/N', max_length=250, null=True, verbose_name='Dirección'),
        ),
    ]
