# Generated by Django 5.2.15 on 2026-07-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_configuracionfacturacion_factura_emisor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuento_porcentaje',
            field=models.IntegerField(default=0, verbose_name='Porcentaje de Descuento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal_neto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal Neto Afectado'),
        ),
    ]
