# Generated by Django 5.2.15 on 2026-07-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_factura_descuento_porcentaje_factura_subtotal_neto'),
        ('menu', '0005_alter_categoriasplato_nombre_categoria'),
        ('pedidos', '0002_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_pedido',
            field=models.OneToOneField(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='pedidos.gestionpedido'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='id_platillo',
            field=models.ForeignKey(blank=True, db_column='id_platillo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.gestionplatillo'),
        ),
    ]
