# Generated by Django 5.2.15 on 2026-07-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_factura_id_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Principal'),
        ),
    ]
