# Generated by Django 5.2.15 on 2026-07-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_configuracionfacturacion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacturacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Principal'),
        ),
    ]
