# Generated by Django 5.2.15 on 2026-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_configuracionfacturacion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='lema_restaurante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lema del Restaurante'),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='logo_restaurante',
            field=models.ImageField(blank=True, null=True, upload_to='logos_marca/', verbose_name='Logo del Restaurante'),
        ),
    ]
