# Generated by Django 5.2.15 on 2026-07-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_configuracionfacturacion_lema_restaurante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionfacturacion',
            name='lema_restaurante',
        ),
    ]
