# Generated by Django 6.0.6 on 2026-06-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_categoriasplato_nombre_categoria'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionPedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('en_preparacion', 'En Preparación'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_preparacion', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('id_mesa', models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.RESTRICT, to='mesas.mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'gestion_pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_platillo', models.ForeignKey(db_column='id_platillo', on_delete=django.db.models.deletion.RESTRICT, to='menu.gestionplatillo')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.gestionpedido')),
            ],
            options={
                'verbose_name': 'Detaille de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado_comanda', models.CharField(choices=[('pendiente', 'Pendiente'), ('lista', 'Lista')], default='pendiente', max_length=20)),
                ('nota_cocina', models.TextField(blank=True, db_column='nota_cocina', null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='pedidos.gestionpedido')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'comanda',
            },
        ),
    ]
