# Generated by Django 5.2.15 on 2026-07-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_categoriasplato_nombre_categoria'),
        ('mesas', '0003_zonamesa_alter_mesa_ubicacion'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_platillo',
            field=models.ForeignKey(blank=True, db_column='id_platillo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.gestionplatillo'),
        ),
        migrations.AlterField(
            model_name='gestionpedido',
            name='id_mesa',
            field=models.ForeignKey(blank=True, db_column='id_mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa'),
        ),
    ]
