# Generated by Django 6.0.6 on 2026-06-17 21:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasPlato',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Plato',
                'verbose_name_plural': 'Categorías de Platos',
                'db_table': 'categorias_plato',
            },
        ),
        migrations.CreateModel(
            name='GestionPlatillo',
            fields=[
                ('id_platillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_platillo', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu/platillos/')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='platillos', to='menu.categoriasplato')),
            ],
            options={
                'verbose_name': 'Gestión de Platillo',
                'verbose_name_plural': 'Gestión de Platillos',
                'db_table': 'gestion_platillo',
            },
        ),
    ]
