# Generated by Django 6.0.6 on 2026-06-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasplato',
            name='nombre_categoria',
            field=models.CharField(choices=[('Entradas', 'Entradas'), ('Sopas', 'Sopas'), ('Platos fuertes', 'Platos fuertes'), ('Parrilladas', 'Parrilladas'), ('Mariscos', 'Mariscos'), ('Postres', 'Postres'), ('Bebidas', 'Bebidas'), ('Cócteles', 'Cócteles'), ('Comida rápida', 'Comida rápida')], max_length=100, unique=True),
        ),
    ]
