# Generated by Django 5.2.15 on 2026-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_categoriasplato_nombre_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionplatillo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
