# Generated by Django 5.2.15 on 2026-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_gestionplatillo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionplatillo',
            name='nombre_platillo',
            field=models.CharField(max_length=150),
        ),
    ]
