# Generated by Django 5.2.15 on 2026-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_gestionplatillo_nombre_platillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasplato',
            name='nombre_categoria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
