# Generated by Django 5.2.15 on 2026-06-26 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula',
            field=models.BigIntegerField(default=9999999999, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(default=999999999, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(default='999999999', max_length=255),
            preserve_default=False,
        ),
    ]
