# Generated by Django 5.2.15 on 2026-06-26 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_cedula_reserva_correo_reserva_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
    ]
