# Generated by Django 5.2.15 on 2026-06-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_cedula_alter_reserva_telefono'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('mesa', 'fecha', 'hora'), name='unique_reserva_mesa_fecha_hora'),
        ),
    ]
