# Generated by Django 5.2.15 on 2026-07-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_unique_reserva_mesa_fecha_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cliente',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombres',
            field=models.CharField(default='1', max_length=150),
            preserve_default=False,
        ),
    ]
