# Generated by Django 5.2.15 on 2026-06-20 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número de Mesa')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad (Personas)')),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=15)),
                ('ubicacion', models.CharField(choices=[('salon_principal', 'Salón Principal'), ('terraza', 'Terraza'), ('vip', 'Zona VIP')], default='salon_principal', max_length=30)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente / Grupo')),
                ('mesero_assigned', models.ForeignKey(blank=True, limit_choices_to={'rol': 'mesero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mesero Asignado')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
    ]
