# Generated by Django 5.2.15 on 2026-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='cliente_cedula',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula del Cliente'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='cliente_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Cliente'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Cliente'),
        ),
    ]
