# Generated by Django 5.2.15 on 2026-06-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_cliente_cedula_mesa_cliente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaMesa',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Zona')),
            ],
            options={
                'verbose_name': 'Zona de Mesa',
                'verbose_name_plural': 'Zonas de Mesas',
                'db_table': 'zonas_mesa',
                'ordering': ['nombre_zona'],
            },
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_column='id_zona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='mesas.zonamesa', verbose_name='Ubicación / Zona'),
        ),
    ]
