# Generated by Django 5.2.15 on 2026-07-09 14:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_zonamesa_alter_mesa_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Mesa Activa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad (Personas)'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Mesa'),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('numero',), name='unique_numero_mesa_activa'),
        ),
    ]
