# Generated by Django 6.0.6 on 2026-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('jefe_cocina', 'Jefe de Cocina'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
