# Generated by Django 6.0.6 on 2026-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('modulo_dashboard', 'Acceso al módulo de Dashboard'), ('modulo_menu', 'Acceso al módulo de Menú'), ('modulo_mesas', 'Acceso al módulo de Mesas'), ('modulo_reservas', 'Acceso al módulo de Reservas'), ('modulo_pedidos', 'Acceso al módulo de Pedidos'), ('modulo_cocina', 'Acceso al módulo de Cocina'), ('modulo_facturacion', 'Acceso al módulo de Facturación'), ('modulo_reportes', 'Acceso al módulo de Reportes')]},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('jefe_cocina', 'Jefe de Cocina')], default='cliente', max_length=20),
        ),
    ]
