# Generated by Django 5.2.15 on 2026-06-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_options_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('secretario', 'Secretario'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('jefe_cocina', 'Jefe de Cocina')], default='cliente', max_length=20),
        ),
    ]
