# Generated by Django 5.2.15 on 2026-06-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('modulo_usuarios', 'Acceso al módulo de Usuarios'), ('modulo_dashboard', 'Acceso al módulo de Dashboard'), ('modulo_menu', 'Acceso al módulo de Menú'), ('modulo_mesas', 'Acceso al módulo de Mesas'), ('modulo_reservas', 'Acceso al módulo de Reservas'), ('modulo_pedidos', 'Acceso al módulo de Pedidos'), ('modulo_cocina', 'Acceso al módulo de Cocina'), ('modulo_facturacion', 'Acceso al módulo de Facturación'), ('modulo_reportes', 'Acceso al módulo de Reportes')]},
        ),
    ]
