# Generated by Django 5.2.15 on 2026-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_anonimo',
            field=models.BooleanField(default=False, verbose_name='¿Está anonimizado?'),
        ),
    ]
