# Generated by Django 5.2.15 on 2026-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado_comanda', models.CharField(default='pendiente', max_length=20)),
                ('nota_cocina', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos_comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionPedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(default='en_preparacion', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(default='libre', max_length=15)),
            ],
            options={
                'db_table': 'mesas_mesa',
                'managed': False,
            },
        ),
    ]
