# Generated by Django 5.2.15 on 2026-07-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditoria',
            table='auditoria',
        ),
    ]
