# Generated by Django 5.2.15 on 2026-07-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditoria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(choices=[('menu', 'Menú'), ('pedidos', 'Pedidos'), ('reservas', 'Reservas'), ('usuarios', 'Usuarios'), ('facturacion', 'Facturación'), ('mesas', 'Mesas')], max_length=20),
        ),
    ]
